config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
  resources :reviews
  end
  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :restaurants, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:title, :tel, :address, :url)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])

  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end



  def create
    @review= Review.new(review_params)
    @review.user_id = current_user.id
    @review.restaurant_id = params[:restaurant_id]
    if @review.save
      redirect_to @review.restaurant
    else
      render :new
    end
  end

 def destroy
  @review = Review.find(params[:id])
  @comment.destroy
 end

 private
 def review_params
  params.require(:review).permit(
    :body,
    :rate)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'スパル食べログ', root_path, class: "navbar-brand" %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li><%= link_to '設定変更', edit_user_registration_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
          <li><%= link_to '新規登録', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpartaTabelog1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>
<h1>レストラン一覧</h1>
<% @restaurants.each do |restaurant| %>







<div class="panel panel-default">
  <div class="panel-heading"><%= link_to restaurant.title, restaurant %></div>
  <div class="panel-body">


  </div>
</div>







    <% end %>
<button type="button" class="btn btn-default"><%= link_to '新しくお店を登録する', new_restaurant_path %></button>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">店舗情報</div>


  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item"><strong>店名：</strong><%= @restaurant.title %></li>
    <li class="list-group-item"><strong>電話番号:</strong><%= @restaurant.tel %></li>
    <li class="list-group-item"><strong>住所:</strong><%= @restaurant.address %></li>
    <li class="list-group-item"><storng>ＵＲＬ:</storng><%= @restaurant.url %></li>
  </ul>
</div>




<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">レビュー一覧</div>

<!-- <p id="notice"><%= notice %></p> -->
<% @restaurant.reviews.each do |review| %>
  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item"><%= review.body %><%= review.rate %></li>

  </ul>
</div>

<% end %>
<button class="btn btn-default" type="submit"><%= link_to 'レストラン情報編集', edit_restaurant_path(@restaurant) %></button>
<button class="btn btn-default" type="submit"><%= link_to '戻る', restaurants_path %></button>
<button class="btn btn-default" type="submit"><%= link_to 'レビューを書く', new_restaurant_review_path(@restaurant) %></button>
















    <hr>
    <h2>レビューを残したユーザー一覧</h2>
    <%# throughオプションのおかげで、RestaurantはReviewを介してUserにアクセスできる  %>

    <% @restaurant.users.each do |user| %>
    <p><%= user.name %>

    </p>

    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
 <div class="form-group">
  <%= f.label :body, 'レビュー' %><br>
  <%= f.text_area :body, class: "form-controll" %>
 </div>
 <div class="form-group">
  <%= f.label :rate, '評価' %><br>
  <%= f.select :rate, {"１点" => "1", "２点" => "2", "３点" => "3", "４点" => "4", "５点" => "5"}  %>


 </div>
 <%= f.submit "レビューを投稿する" %>
 <% end %>

</div>

app/views/reviews/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レビューの編集</h1>
    <%= render 'form' %>
    <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#delete-review">レビューを削除する</button>
  </div>
</div>

<!-- 下記のモーダルは通常は隠れているので、どこに書いてもＯＫ -->
<div class="modal fade" id="delete-review">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">レビューの削除</h4>
      </div>
      <div class="modal-body">
        <p><%= @review %>を削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @review, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="row">
 <div class="col-lg-12">
<h1>ニューレビュー登録:<%= @restaurant.title %></h1>


  </div>
  <%= render 'form' %>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @restaurant.title %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @restaurant.tel %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Url:</strong>
  <%= @restaurant.url %>
</p>



<%= link_to '編集', edit_restaurant_path(@restaurant) %> |
<%= link_to '戻る', restaurants_path %>
<%= link_to 'レビューを書く', new_restaurant_review_path(@restaurant) %> |

    <hr>

    <h2>レビュー一覧</h2>
    <% @restaurant.reviews.each do |review| %>
      <p>
        <%= review.body %> <br>
        <%= review.rate %><br>

      </p>
    <% end %>
    <hr>
    <!-- <h2>レビューを残したユーザー一覧</h2> -->
    <%# throughオプションのおかげで、RestaurantはReviewを介してUserにアクセスできる  %>
    <!-- <% @restaurant.users.each do |user| %> -->

    <!-- <% end %> -->
  </div>
</div>